image: Visual Studio 2022

services:
  - docker
  
test_script:
#- ps: .\test.ps1
  - ps: >-
      while ($i -lt (300)) {
      $i +=1
  
      $dockerSvc = (Get-Service com.docker.service -ErrorAction SilentlyContinue)
      if ((Get-Process 'Docker Desktop' -ErrorAction SilentlyContinue) -and $dockerSvc -and $dockerSvc.status -eq 'Running') {
        $finished = $true
        Write-Host "Docker started!"
        break
      }
      Write-Host "Retrying in 5 seconds..."
      sleep 5;
    }
    
  - ps: >-
      cd src\transparency.infrastructure.whoislookupservice

      docker build -t whoislookup-image -f Dockerfile .

build: off

on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
