test_script:
- where docker-compose



- ps: $images = (docker images)
- ps: $images
#- ps: if ($images.length -ne 7) { throw "Wrong number of images!"; }
#- ps: if ($images[1].indexOf('microsoft/windowsservercore') -eq -1 -or $images[3].indexOf('microsoft/nanoserver') -eq -1) { throw "Images are incomplete!"; }

- ps: $run1 = (docker run microsoft/windowsservercore cmd /c dir)
- ps: $run1
- ps: if ($run1[3].indexOf('Directory of C:\') -eq -1) { throw "Error running microsoft/windowsservercore container"; }

- ps: $run2 = (docker run microsoft/nanoserver cmd /c dir)
- ps: $run2
- ps: if ($run2[3].indexOf('Directory of C:\') -eq -1) { throw "Error running microsoft/nanoserver container"; }

- ps: $containers = (docker ps -a -q)
- ps: $containers
- ps: if ($containers.length -ne 2) { throw "Wrong number of containers!"; }

build: off
