image: Visual Studio 2022

init: 
  - ps: Stop-Service -Name *Docker*
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#services:
 # - docker

before_build:
  
  - ps: Start-Process -FilePath "$env:ProgramFiles\Docker\Docker\Docker Desktop.exe" -Verb runas

 # - ps: Stop-Service -Name *Docker*
 # - ps: Start-Service -Name *Docker*
  #- ps: .\service-test.ps1
 # - ps: >-
  #    & "$env:ProgramFiles\Docker\Docker\Docker Desktop.exe"
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))   
  #- ps: Switch-DockerWindows
  
build_script:
  - ps: docker build -t hello-world-image .
  
test_script:
#- ps: .\test.ps1
  #- ps: .\service-test.ps1


on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
