image: Visual Studio 2019

insstall: 
- ps: |
    Write-Host "Stopping Docker"
    Stop-Service docker

    Write-Host "Re-registering Docker with experimental features enabled"
    dockerd --unregister-service
    dockerd --register-service --experimental
    Start-Service docker
    Write-Host "Starting Docker"
    Start-Service docker
    
test_script:
- ps: .\test.ps1

build: off

on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
