image: Visual Studio 2022

services:
  - docker
  
test_script:
#- ps: .\test.ps1
  #- ps: .\service-test.ps1

build_script:
  - ps: docker build -t hello-world-image .

on_failure:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
